include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-cloud-control
PKG_VERSION:=1.0
PKG_RELEASE:=1

LUCI_TITLE:=LUCI support for cloud-control
LUCI_DEPENDS:=+cloud-control
LUCI_PKGARCH=all
PKG_MAINTAINER=skadi <love@skadi.ltd>

include $(TOPDIR)/feeds/luci/luci.mk